name: Linter

on: [push, pull_request]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://hawkingrei/tind:v5.2.1
        name: __all__
        with:
          args: |
            bash -c "tox -e lint"
